/*
 * This source file was generated by the Gradle 'init' task
 */
package project1;

import javax.swing.JFrame;

public class App {

    public static void main(String[] args) {
        JFrame frame = new JFrame("My Swing Window");
        frame.setSize(400, 300);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }
    
}
